//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.18 at 12:33:08 AM EDT 
//


package org.greenbuttonalliance.espi.resourceserver.web.model.retailcustomer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * [extension] Customer action notification (e.g., delinquency, move in, move out)
 * 
 * <p>Java class for AccountNotification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccountNotification"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://naesb.org/espi/customer}Object"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="methodKind" type="{http://naesb.org/espi/customer}NotificationMethodKind"/&gt;
 *         &lt;element name="time" type="{http://naesb.org/espi/customer}TimeType"/&gt;
 *         &lt;element name="note" type="{http://naesb.org/espi/customer}String256"/&gt;
 *         &lt;element name="customerNotificationKind" type="{http://naesb.org/espi/customer}String256"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccountNotification", propOrder = {
    "methodKind",
    "time",
    "note",
    "customerNotificationKind"
})
public class AccountNotification
    extends Object
{

    @XmlElement(required = true)
    protected String methodKind;
    protected long time;
    @XmlElement(required = true)
    protected String note;
    @XmlElement(required = true)
    protected String customerNotificationKind;

    /**
     * Gets the value of the methodKind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethodKind() {
        return methodKind;
    }

    /**
     * Sets the value of the methodKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethodKind(String value) {
        this.methodKind = value;
    }

    /**
     * Gets the value of the time property.
     * 
     */
    public long getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     */
    public void setTime(long value) {
        this.time = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the customerNotificationKind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerNotificationKind() {
        return customerNotificationKind;
    }

    /**
     * Sets the value of the customerNotificationKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerNotificationKind(String value) {
        this.customerNotificationKind = value;
    }

}
