/*
 *
 *      Copyright (c) 2020 Green Button Alliance, Inc.
 *
 *      Licensed under the Apache License, Version 2.0 (the "License");
 *      you may not use this file except in compliance with the License.
 *      You may obtain a copy of the License at
 *
 *          http://www.apache.org/licenses/LICENSE-2.0
 *
 *      Unless required by applicable law or agreed to in writing, software
 *      distributed under the License is distributed on an "AS IS" BASIS,
 *      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *      See the License for the specific language governing permissions and
 *      limitations under the License.
 *
 *
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.18 at 12:33:08 AM EDT 
//


package org.greenbuttonalliance.espi.resourceserver.web.model.retailcustomer;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.greenbuttonalliance.espi.resourceserver.web.model.retailcustomer package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final String NAESB_CUSTOMER_NAMESPACE_URI = "http://naesb.org/espi/customer";
    private static final String ATOMNAMESPACEURI = "http://www.w3.org/2005/Atom";

    private static final QName _AcceptanceTest_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "AcceptanceTest");
    private static final QName _AccountNotification_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "AccountNotification");
    private static final QName _Agreement_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "Agreement");
    private static final QName _Asset_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "Asset");
    private static final QName _AssetContainer_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "AssetContainer");
    private static final QName _BatchItemInfo_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "BatchItemInfo");
    private static final QName _BatchList_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "BatchList");
    private static final QName _Customer_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "Customer");
    private static final QName _CustomerAccount_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "CustomerAccount");
    private static final QName _CustomerAgreement_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "CustomerAgreement");
    private static final QName _DateTimeInterval_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "DateTimeInterval");
    private static final QName _DemandResponseProgram_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "DemandResponseProgram");
    private static final QName _Document_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "Document");
    private static final QName _ElectronicAddress_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "ElectronicAddress");
    private static final QName _EndDevice_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "EndDevice");
    private static final QName _IdentifiedObject_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "IdentifiedObject");
    private static final QName _LifecycleDate_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "LifecycleDate");
    private static final QName _LocalTimeParameters_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "LocalTimeParameters");
    private static final QName _Location_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "Location");
    private static final QName _Meter_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "Meter");
    private static final QName _MeterMultiplier_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "MeterMultiplier");
    private static final QName _Object_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "Object");
    private static final QName _Organisation_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "Organisation");
    private static final QName _OrganisationRole_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "OrganisationRole");
    private static final QName _PositionPoint_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "PositionPoint");
    private static final QName _PricingStructure_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "PricingStructure");
    private static final QName _Priority_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "Priority");
    private static final QName _ProgramDate_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "ProgramDate");
    private static final QName _ProgramDateIdMapping_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "ProgramDateIdMapping");
    private static final QName _ProgramDateIdMappings_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "ProgramDateIdMappings");
    private static final QName _ServiceLocation_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "ServiceLocation");
    private static final QName _ServiceSupplier_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "ServiceSupplier");
    private static final QName _Status_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "Status");
    private static final QName _StreetAddress_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "StreetAddress");
    private static final QName _StreetDetail_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "StreetDetail");
    private static final QName _SummaryMeasurement_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "SummaryMeasurement");
    private static final QName _TelephoneNumber_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "TelephoneNumber");
    private static final QName _TimeConfiguration_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "TimeConfiguration");
    private static final QName _TownDetail_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "TownDetail");
    private static final QName _UsagePoint_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "UsagePoint");
    private static final QName _UsagePoints_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "UsagePoints");
    private static final QName _WorkLocation_QNAME = new QName(NAESB_CUSTOMER_NAMESPACE_URI, "WorkLocation");
    private static final QName _Feed_QNAME = new QName(ATOMNAMESPACEURI, "feed");
    private static final QName _Entry_QNAME = new QName(ATOMNAMESPACEURI, "entry");
    private static final QName _SourceTypeAuthor_QNAME = new QName(ATOMNAMESPACEURI, "author");
    private static final QName _SourceTypeCategory_QNAME = new QName(ATOMNAMESPACEURI, "category");
    private static final QName _SourceTypeContributor_QNAME = new QName(ATOMNAMESPACEURI, "contributor");
    private static final QName _SourceTypeGenerator_QNAME = new QName(ATOMNAMESPACEURI, "generator");
    private static final QName _SourceTypeIcon_QNAME = new QName(ATOMNAMESPACEURI, "icon");
    private static final QName _SourceTypeId_QNAME = new QName(ATOMNAMESPACEURI, "id");
    private static final QName _SourceTypeLink_QNAME = new QName(ATOMNAMESPACEURI, "link");
    private static final QName _SourceTypeLogo_QNAME = new QName(ATOMNAMESPACEURI, "logo");
    private static final QName _SourceTypeRights_QNAME = new QName(ATOMNAMESPACEURI, "rights");
    private static final QName _SourceTypeSubtitle_QNAME = new QName(ATOMNAMESPACEURI, "subtitle");
    private static final QName _SourceTypeTitle_QNAME = new QName(ATOMNAMESPACEURI, "title");
    private static final QName _SourceTypeUpdated_QNAME = new QName(ATOMNAMESPACEURI, "updated");
    private static final QName _PersonTypeName_QNAME = new QName(ATOMNAMESPACEURI, "name");
    private static final QName _PersonTypeUri_QNAME = new QName(ATOMNAMESPACEURI, "uri");
    private static final QName _PersonTypeEmail_QNAME = new QName(ATOMNAMESPACEURI, "email");
    private static final QName _EntryTypeContent_QNAME = new QName(ATOMNAMESPACEURI, "content");
    private static final QName _EntryTypePublished_QNAME = new QName(ATOMNAMESPACEURI, "published");
    private static final QName _EntryTypeSource_QNAME = new QName(ATOMNAMESPACEURI, "source");
    private static final QName _EntryTypeSummary_QNAME = new QName(ATOMNAMESPACEURI, "summary");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * org.greenbuttonalliance.espi.resourceserver.web.model.retailcustomer
     * 
     */
    public ObjectFactory() {
        throw new UnsupportedOperationException();
    }

    /**
     * Create an instance of {@link AcceptanceTest }
     * 
     */
    public AcceptanceTest createAcceptanceTest() {
        return new AcceptanceTest();
    }

    /**
     * Create an instance of {@link AccountNotification }
     * 
     */
    public AccountNotification createAccountNotification() {
        return new AccountNotification();
    }

    /**
     * Create an instance of {@link Agreement }
     * 
     */
    public Agreement createAgreement() {
        return new Agreement();
    }

    /**
     * Create an instance of {@link Asset }
     * 
     */
    public Asset createAsset() {
        return new Asset();
    }

    /**
     * Create an instance of {@link AssetContainer }
     * 
     */
    public AssetContainer createAssetContainer() {
        return new AssetContainer();
    }

    /**
     * Create an instance of {@link BatchItemInfo }
     * 
     */
    public BatchItemInfo createBatchItemInfo() {
        return new BatchItemInfo();
    }

    /**
     * Create an instance of {@link BatchListType }
     * 
     */
    public BatchListType createBatchListType() {
        return new BatchListType();
    }

    /**
     * Create an instance of {@link Customer }
     * 
     */
    public Customer createCustomer() {
        return new Customer();
    }

    /**
     * Create an instance of {@link CustomerAccount }
     * 
     */
    public CustomerAccount createCustomerAccount() {
        return new CustomerAccount();
    }

    /**
     * Create an instance of {@link CustomerAgreement }
     * 
     */
    public CustomerAgreement createCustomerAgreement() {
        return new CustomerAgreement();
    }

    /**
     * Create an instance of {@link DateTimeInterval }
     * 
     */
    public DateTimeInterval createDateTimeInterval() {
        return new DateTimeInterval();
    }

    /**
     * Create an instance of {@link DemandResponseProgram }
     * 
     */
    public DemandResponseProgram createDemandResponseProgram() {
        return new DemandResponseProgram();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link ElectronicAddress }
     * 
     */
    public ElectronicAddress createElectronicAddress() {
        return new ElectronicAddress();
    }

    /**
     * Create an instance of {@link EndDevice }
     * 
     */
    public EndDevice createEndDevice() {
        return new EndDevice();
    }

    /**
     * Create an instance of {@link IdentifiedObject }
     * 
     */
    public IdentifiedObject createIdentifiedObject() {
        return new IdentifiedObject();
    }

    /**
     * Create an instance of {@link LifecycleDate }
     * 
     */
    public LifecycleDate createLifecycleDate() {
        return new LifecycleDate();
    }

    /**
     * Create an instance of {@link TimeConfiguration }
     * 
     */
    public TimeConfiguration createTimeConfiguration() {
        return new TimeConfiguration();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link Meter }
     * 
     */
    public Meter createMeter() {
        return new Meter();
    }

    /**
     * Create an instance of {@link MeterMultiplier }
     * 
     */
    public MeterMultiplier createMeterMultiplier() {
        return new MeterMultiplier();
    }

    /**
     * Create an instance of {@link Object }
     * 
     */
    public Object createObject() {
        return new Object();
    }

    /**
     * Create an instance of {@link Organisation }
     * 
     */
    public Organisation createOrganisation() {
        return new Organisation();
    }

    /**
     * Create an instance of {@link OrganisationRole }
     * 
     */
    public OrganisationRole createOrganisationRole() {
        return new OrganisationRole();
    }

    /**
     * Create an instance of {@link PositionPoint }
     * 
     */
    public PositionPoint createPositionPoint() {
        return new PositionPoint();
    }

    /**
     * Create an instance of {@link PricingStructure }
     * 
     */
    public PricingStructure createPricingStructure() {
        return new PricingStructure();
    }

    /**
     * Create an instance of {@link Priority }
     * 
     */
    public Priority createPriority() {
        return new Priority();
    }

    /**
     * Create an instance of {@link ProgramDate }
     * 
     */
    public ProgramDate createProgramDate() {
        return new ProgramDate();
    }

    /**
     * Create an instance of {@link ProgramDateIdMapping }
     * 
     */
    public ProgramDateIdMapping createProgramDateIdMapping() {
        return new ProgramDateIdMapping();
    }

    /**
     * Create an instance of {@link ProgramDateIdMappings }
     * 
     */
    public ProgramDateIdMappings createProgramDateIdMappings() {
        return new ProgramDateIdMappings();
    }

    /**
     * Create an instance of {@link ServiceLocation }
     * 
     */
    public ServiceLocation createServiceLocation() {
        return new ServiceLocation();
    }

    /**
     * Create an instance of {@link ServiceSupplier }
     * 
     */
    public ServiceSupplier createServiceSupplier() {
        return new ServiceSupplier();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link StreetAddress }
     * 
     */
    public StreetAddress createStreetAddress() {
        return new StreetAddress();
    }

    /**
     * Create an instance of {@link StreetDetail }
     * 
     */
    public StreetDetail createStreetDetail() {
        return new StreetDetail();
    }

    /**
     * Create an instance of {@link SummaryMeasurement }
     * 
     */
    public SummaryMeasurement createSummaryMeasurement() {
        return new SummaryMeasurement();
    }

    /**
     * Create an instance of {@link TelephoneNumber }
     * 
     */
    public TelephoneNumber createTelephoneNumber() {
        return new TelephoneNumber();
    }

    /**
     * Create an instance of {@link TownDetail }
     * 
     */
    public TownDetail createTownDetail() {
        return new TownDetail();
    }

    /**
     * Create an instance of {@link UsagePoint }
     * 
     */
    public UsagePoint createUsagePoint() {
        return new UsagePoint();
    }

    /**
     * Create an instance of {@link UsagePoints }
     * 
     */
    public UsagePoints createUsagePoints() {
        return new UsagePoints();
    }

    /**
     * Create an instance of {@link WorkLocation }
     * 
     */
    public WorkLocation createWorkLocation() {
        return new WorkLocation();
    }

    /**
     * Create an instance of {@link FeedType }
     * 
     */
    public FeedType createFeedType() {
        return new FeedType();
    }

    /**
     * Create an instance of {@link EntryType }
     * 
     */
    public EntryType createEntryType() {
        return new EntryType();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link ContentType }
     * 
     */
    public ContentType createContentType() {
        return new ContentType();
    }

    /**
     * Create an instance of {@link CategoryType }
     * 
     */
    public CategoryType createCategoryType() {
        return new CategoryType();
    }

    /**
     * Create an instance of {@link GeneratorType }
     * 
     */
    public GeneratorType createGeneratorType() {
        return new GeneratorType();
    }

    /**
     * Create an instance of {@link IconType }
     * 
     */
    public IconType createIconType() {
        return new IconType();
    }

    /**
     * Create an instance of {@link IdType }
     * 
     */
    public IdType createIdType() {
        return new IdType();
    }

    /**
     * Create an instance of {@link LinkType }
     * 
     */
    public LinkType createLinkType() {
        return new LinkType();
    }

    /**
     * Create an instance of {@link LogoType }
     * 
     */
    public LogoType createLogoType() {
        return new LogoType();
    }

    /**
     * Create an instance of {@link SourceType }
     * 
     */
    public SourceType createSourceType() {
        return new SourceType();
    }

    /**
     * Create an instance of {@link UriType }
     * 
     */
    public UriType createUriType() {
        return new UriType();
    }

    /**
     * Create an instance of {@link DateTimeType }
     * 
     */
    public DateTimeType createDateTimeType() {
        return new DateTimeType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AcceptanceTest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AcceptanceTest }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "AcceptanceTest")
    public JAXBElement<AcceptanceTest> createAcceptanceTest(AcceptanceTest value) {
        return new JAXBElement<>(_AcceptanceTest_QNAME, AcceptanceTest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccountNotification }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AccountNotification }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "AccountNotification")
    public JAXBElement<AccountNotification> createAccountNotification(AccountNotification value) {
        return new JAXBElement<>(_AccountNotification_QNAME, AccountNotification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Agreement }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Agreement }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "Agreement")
    public JAXBElement<Agreement> createAgreement(Agreement value) {
        return new JAXBElement<>(_Agreement_QNAME, Agreement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Asset }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Asset }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "Asset")
    public JAXBElement<Asset> createAsset(Asset value) {
        return new JAXBElement<>(_Asset_QNAME, Asset.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AssetContainer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AssetContainer }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "AssetContainer")
    public JAXBElement<AssetContainer> createAssetContainer(AssetContainer value) {
        return new JAXBElement<>(_AssetContainer_QNAME, AssetContainer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BatchItemInfo }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BatchItemInfo }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "BatchItemInfo")
    public JAXBElement<BatchItemInfo> createBatchItemInfo(BatchItemInfo value) {
        return new JAXBElement<>(_BatchItemInfo_QNAME, BatchItemInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BatchListType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BatchListType }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "BatchList")
    public JAXBElement<BatchListType> createBatchList(BatchListType value) {
        return new JAXBElement<>(_BatchList_QNAME, BatchListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Customer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Customer }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "Customer")
    public JAXBElement<Customer> createCustomer(Customer value) {
        return new JAXBElement<>(_Customer_QNAME, Customer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerAccount }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CustomerAccount }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "CustomerAccount")
    public JAXBElement<CustomerAccount> createCustomerAccount(CustomerAccount value) {
        return new JAXBElement<>(_CustomerAccount_QNAME, CustomerAccount.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerAgreement }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CustomerAgreement }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "CustomerAgreement")
    public JAXBElement<CustomerAgreement> createCustomerAgreement(CustomerAgreement value) {
        return new JAXBElement<>(_CustomerAgreement_QNAME, CustomerAgreement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateTimeInterval }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DateTimeInterval }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "DateTimeInterval")
    public JAXBElement<DateTimeInterval> createDateTimeInterval(DateTimeInterval value) {
        return new JAXBElement<>(_DateTimeInterval_QNAME, DateTimeInterval.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DemandResponseProgram }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DemandResponseProgram }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "DemandResponseProgram")
    public JAXBElement<DemandResponseProgram> createDemandResponseProgram(DemandResponseProgram value) {
        return new JAXBElement<>(_DemandResponseProgram_QNAME, DemandResponseProgram.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "Document")
    public JAXBElement<Document> createDocument(Document value) {
        return new JAXBElement<>(_Document_QNAME, Document.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElectronicAddress }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ElectronicAddress }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "ElectronicAddress")
    public JAXBElement<ElectronicAddress> createElectronicAddress(ElectronicAddress value) {
        return new JAXBElement<>(_ElectronicAddress_QNAME, ElectronicAddress.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndDevice }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link EndDevice }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "EndDevice")
    public JAXBElement<EndDevice> createEndDevice(EndDevice value) {
        return new JAXBElement<>(_EndDevice_QNAME, EndDevice.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentifiedObject }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link IdentifiedObject }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "IdentifiedObject")
    public JAXBElement<IdentifiedObject> createIdentifiedObject(IdentifiedObject value) {
        return new JAXBElement<>(_IdentifiedObject_QNAME, IdentifiedObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LifecycleDate }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link LifecycleDate }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "LifecycleDate")
    public JAXBElement<LifecycleDate> createLifecycleDate(LifecycleDate value) {
        return new JAXBElement<>(_LifecycleDate_QNAME, LifecycleDate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TimeConfiguration }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TimeConfiguration }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "LocalTimeParameters")
    public JAXBElement<TimeConfiguration> createLocalTimeParameters(TimeConfiguration value) {
        return new JAXBElement<>(_LocalTimeParameters_QNAME, TimeConfiguration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Location }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Location }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "Location")
    public JAXBElement<Location> createLocation(Location value) {
        return new JAXBElement<>(_Location_QNAME, Location.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Meter }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Meter }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "Meter")
    public JAXBElement<Meter> createMeter(Meter value) {
        return new JAXBElement<>(_Meter_QNAME, Meter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MeterMultiplier }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MeterMultiplier }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "MeterMultiplier")
    public JAXBElement<MeterMultiplier> createMeterMultiplier(MeterMultiplier value) {
        return new JAXBElement<>(_MeterMultiplier_QNAME, MeterMultiplier.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "Object")
    public JAXBElement<Object> createObject(Object value) {
        return new JAXBElement<>(_Object_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Organisation }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Organisation }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "Organisation")
    public JAXBElement<Organisation> createOrganisation(Organisation value) {
        return new JAXBElement<>(_Organisation_QNAME, Organisation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganisationRole }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OrganisationRole }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "OrganisationRole")
    public JAXBElement<OrganisationRole> createOrganisationRole(OrganisationRole value) {
        return new JAXBElement<>(_OrganisationRole_QNAME, OrganisationRole.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PositionPoint }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PositionPoint }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "PositionPoint")
    public JAXBElement<PositionPoint> createPositionPoint(PositionPoint value) {
        return new JAXBElement<>(_PositionPoint_QNAME, PositionPoint.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PricingStructure }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PricingStructure }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "PricingStructure")
    public JAXBElement<PricingStructure> createPricingStructure(PricingStructure value) {
        return new JAXBElement<>(_PricingStructure_QNAME, PricingStructure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Priority }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Priority }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "Priority")
    public JAXBElement<Priority> createPriority(Priority value) {
        return new JAXBElement<>(_Priority_QNAME, Priority.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProgramDate }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ProgramDate }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "ProgramDate")
    public JAXBElement<ProgramDate> createProgramDate(ProgramDate value) {
        return new JAXBElement<>(_ProgramDate_QNAME, ProgramDate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProgramDateIdMapping }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ProgramDateIdMapping }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "ProgramDateIdMapping")
    public JAXBElement<ProgramDateIdMapping> createProgramDateIdMapping(ProgramDateIdMapping value) {
        return new JAXBElement<>(_ProgramDateIdMapping_QNAME, ProgramDateIdMapping.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProgramDateIdMappings }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ProgramDateIdMappings }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "ProgramDateIdMappings")
    public JAXBElement<ProgramDateIdMappings> createProgramDateIdMappings(ProgramDateIdMappings value) {
        return new JAXBElement<>(_ProgramDateIdMappings_QNAME, ProgramDateIdMappings.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceLocation }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ServiceLocation }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "ServiceLocation")
    public JAXBElement<ServiceLocation> createServiceLocation(ServiceLocation value) {
        return new JAXBElement<>(_ServiceLocation_QNAME, ServiceLocation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceSupplier }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ServiceSupplier }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "ServiceSupplier")
    public JAXBElement<ServiceSupplier> createServiceSupplier(ServiceSupplier value) {
        return new JAXBElement<>(_ServiceSupplier_QNAME, ServiceSupplier.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Status }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Status }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "Status")
    public JAXBElement<Status> createStatus(Status value) {
        return new JAXBElement<>(_Status_QNAME, Status.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StreetAddress }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StreetAddress }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "StreetAddress")
    public JAXBElement<StreetAddress> createStreetAddress(StreetAddress value) {
        return new JAXBElement<>(_StreetAddress_QNAME, StreetAddress.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StreetDetail }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StreetDetail }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "StreetDetail")
    public JAXBElement<StreetDetail> createStreetDetail(StreetDetail value) {
        return new JAXBElement<>(_StreetDetail_QNAME, StreetDetail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SummaryMeasurement }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SummaryMeasurement }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "SummaryMeasurement")
    public JAXBElement<SummaryMeasurement> createSummaryMeasurement(SummaryMeasurement value) {
        return new JAXBElement<>(_SummaryMeasurement_QNAME, SummaryMeasurement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TelephoneNumber }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TelephoneNumber }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "TelephoneNumber")
    public JAXBElement<TelephoneNumber> createTelephoneNumber(TelephoneNumber value) {
        return new JAXBElement<>(_TelephoneNumber_QNAME, TelephoneNumber.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TimeConfiguration }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TimeConfiguration }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "TimeConfiguration")
    public JAXBElement<TimeConfiguration> createTimeConfiguration(TimeConfiguration value) {
        return new JAXBElement<>(_TimeConfiguration_QNAME, TimeConfiguration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TownDetail }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TownDetail }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "TownDetail")
    public JAXBElement<TownDetail> createTownDetail(TownDetail value) {
        return new JAXBElement<>(_TownDetail_QNAME, TownDetail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UsagePoint }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UsagePoint }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "UsagePoint")
    public JAXBElement<UsagePoint> createUsagePoint(UsagePoint value) {
        return new JAXBElement<>(_UsagePoint_QNAME, UsagePoint.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UsagePoints }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UsagePoints }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "UsagePoints")
    public JAXBElement<UsagePoints> createUsagePoints(UsagePoints value) {
        return new JAXBElement<>(_UsagePoints_QNAME, UsagePoints.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WorkLocation }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link WorkLocation }{@code >}
     */
    @XmlElementDecl(namespace = NAESB_CUSTOMER_NAMESPACE_URI, name = "WorkLocation")
    public JAXBElement<WorkLocation> createWorkLocation(WorkLocation value) {
        return new JAXBElement<>(_WorkLocation_QNAME, WorkLocation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FeedType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FeedType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "feed")
    public JAXBElement<FeedType> createFeed(FeedType value) {
        return new JAXBElement<>(_Feed_QNAME, FeedType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntryType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link EntryType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "entry")
    public JAXBElement<EntryType> createEntry(EntryType value) {
        return new JAXBElement<>(_Entry_QNAME, EntryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PersonType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "author", scope = SourceType.class)
    public JAXBElement<PersonType> createSourceTypeAuthor(PersonType value) {
        return new JAXBElement<>(_SourceTypeAuthor_QNAME, PersonType.class, SourceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CategoryType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CategoryType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "category", scope = SourceType.class)
    public JAXBElement<CategoryType> createSourceTypeCategory(CategoryType value) {
        return new JAXBElement<>(_SourceTypeCategory_QNAME, CategoryType.class, SourceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PersonType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "contributor", scope = SourceType.class)
    public JAXBElement<PersonType> createSourceTypeContributor(PersonType value) {
        return new JAXBElement<>(_SourceTypeContributor_QNAME, PersonType.class, SourceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeneratorType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GeneratorType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "generator", scope = SourceType.class)
    public JAXBElement<GeneratorType> createSourceTypeGenerator(GeneratorType value) {
        return new JAXBElement<>(_SourceTypeGenerator_QNAME, GeneratorType.class, SourceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IconType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link IconType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "icon", scope = SourceType.class)
    public JAXBElement<IconType> createSourceTypeIcon(IconType value) {
        return new JAXBElement<>(_SourceTypeIcon_QNAME, IconType.class, SourceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link IdType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "id", scope = SourceType.class)
    public JAXBElement<IdType> createSourceTypeId(IdType value) {
        return new JAXBElement<>(_SourceTypeId_QNAME, IdType.class, SourceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link LinkType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "link", scope = SourceType.class)
    public JAXBElement<LinkType> createSourceTypeLink(LinkType value) {
        return new JAXBElement<>(_SourceTypeLink_QNAME, LinkType.class, SourceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogoType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link LogoType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "logo", scope = SourceType.class)
    public JAXBElement<LogoType> createSourceTypeLogo(LogoType value) {
        return new JAXBElement<>(_SourceTypeLogo_QNAME, LogoType.class, SourceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "rights", scope = SourceType.class)
    public JAXBElement<TextType> createSourceTypeRights(TextType value) {
        return new JAXBElement<>(_SourceTypeRights_QNAME, TextType.class, SourceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "subtitle", scope = SourceType.class)
    public JAXBElement<TextType> createSourceTypeSubtitle(TextType value) {
        return new JAXBElement<>(_SourceTypeSubtitle_QNAME, TextType.class, SourceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "title", scope = SourceType.class)
    public JAXBElement<TextType> createSourceTypeTitle(TextType value) {
        return new JAXBElement<>(_SourceTypeTitle_QNAME, TextType.class, SourceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateTimeType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DateTimeType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "updated", scope = SourceType.class)
    public JAXBElement<DateTimeType> createSourceTypeUpdated(DateTimeType value) {
        return new JAXBElement<>(_SourceTypeUpdated_QNAME, DateTimeType.class, SourceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "name", scope = PersonType.class)
    public JAXBElement<String> createPersonTypeName(String value) {
        return new JAXBElement<>(_PersonTypeName_QNAME, String.class, PersonType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UriType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UriType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "uri", scope = PersonType.class)
    public JAXBElement<UriType> createPersonTypeUri(UriType value) {
        return new JAXBElement<>(_PersonTypeUri_QNAME, UriType.class, PersonType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "email", scope = PersonType.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createPersonTypeEmail(String value) {
        return new JAXBElement<>(_PersonTypeEmail_QNAME, String.class, PersonType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PersonType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "author", scope = EntryType.class)
    public JAXBElement<PersonType> createEntryTypeAuthor(PersonType value) {
        return new JAXBElement<>(_SourceTypeAuthor_QNAME, PersonType.class, EntryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CategoryType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CategoryType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "category", scope = EntryType.class)
    public JAXBElement<CategoryType> createEntryTypeCategory(CategoryType value) {
        return new JAXBElement<>(_SourceTypeCategory_QNAME, CategoryType.class, EntryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ContentType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "content", scope = EntryType.class)
    public JAXBElement<ContentType> createEntryTypeContent(ContentType value) {
        return new JAXBElement<>(_EntryTypeContent_QNAME, ContentType.class, EntryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PersonType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "contributor", scope = EntryType.class)
    public JAXBElement<PersonType> createEntryTypeContributor(PersonType value) {
        return new JAXBElement<>(_SourceTypeContributor_QNAME, PersonType.class, EntryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link IdType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "id", scope = EntryType.class)
    public JAXBElement<IdType> createEntryTypeId(IdType value) {
        return new JAXBElement<>(_SourceTypeId_QNAME, IdType.class, EntryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link LinkType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "link", scope = EntryType.class)
    public JAXBElement<LinkType> createEntryTypeLink(LinkType value) {
        return new JAXBElement<>(_SourceTypeLink_QNAME, LinkType.class, EntryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateTimeType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DateTimeType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "published", scope = EntryType.class)
    public JAXBElement<DateTimeType> createEntryTypePublished(DateTimeType value) {
        return new JAXBElement<>(_EntryTypePublished_QNAME, DateTimeType.class, EntryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "rights", scope = EntryType.class)
    public JAXBElement<TextType> createEntryTypeRights(TextType value) {
        return new JAXBElement<>(_SourceTypeRights_QNAME, TextType.class, EntryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "source", scope = EntryType.class)
    public JAXBElement<TextType> createEntryTypeSource(TextType value) {
        return new JAXBElement<>(_EntryTypeSource_QNAME, TextType.class, EntryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "summary", scope = EntryType.class)
    public JAXBElement<TextType> createEntryTypeSummary(TextType value) {
        return new JAXBElement<>(_EntryTypeSummary_QNAME, TextType.class, EntryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "title", scope = EntryType.class)
    public JAXBElement<TextType> createEntryTypeTitle(TextType value) {
        return new JAXBElement<>(_SourceTypeTitle_QNAME, TextType.class, EntryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateTimeType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DateTimeType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "updated", scope = EntryType.class)
    public JAXBElement<DateTimeType> createEntryTypeUpdated(DateTimeType value) {
        return new JAXBElement<>(_SourceTypeUpdated_QNAME, DateTimeType.class, EntryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PersonType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "author", scope = FeedType.class)
    public JAXBElement<PersonType> createFeedTypeAuthor(PersonType value) {
        return new JAXBElement<>(_SourceTypeAuthor_QNAME, PersonType.class, FeedType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CategoryType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CategoryType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "category", scope = FeedType.class)
    public JAXBElement<CategoryType> createFeedTypeCategory(CategoryType value) {
        return new JAXBElement<>(_SourceTypeCategory_QNAME, CategoryType.class, FeedType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PersonType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "contributor", scope = FeedType.class)
    public JAXBElement<PersonType> createFeedTypeContributor(PersonType value) {
        return new JAXBElement<>(_SourceTypeContributor_QNAME, PersonType.class, FeedType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeneratorType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GeneratorType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "generator", scope = FeedType.class)
    public JAXBElement<GeneratorType> createFeedTypeGenerator(GeneratorType value) {
        return new JAXBElement<>(_SourceTypeGenerator_QNAME, GeneratorType.class, FeedType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IconType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link IconType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "icon", scope = FeedType.class)
    public JAXBElement<IconType> createFeedTypeIcon(IconType value) {
        return new JAXBElement<>(_SourceTypeIcon_QNAME, IconType.class, FeedType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link IdType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "id", scope = FeedType.class)
    public JAXBElement<IdType> createFeedTypeId(IdType value) {
        return new JAXBElement<>(_SourceTypeId_QNAME, IdType.class, FeedType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link LinkType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "link", scope = FeedType.class)
    public JAXBElement<LinkType> createFeedTypeLink(LinkType value) {
        return new JAXBElement<>(_SourceTypeLink_QNAME, LinkType.class, FeedType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogoType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link LogoType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "logo", scope = FeedType.class)
    public JAXBElement<LogoType> createFeedTypeLogo(LogoType value) {
        return new JAXBElement<>(_SourceTypeLogo_QNAME, LogoType.class, FeedType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "rights", scope = FeedType.class)
    public JAXBElement<TextType> createFeedTypeRights(TextType value) {
        return new JAXBElement<>(_SourceTypeRights_QNAME, TextType.class, FeedType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "subtitle", scope = FeedType.class)
    public JAXBElement<TextType> createFeedTypeSubtitle(TextType value) {
        return new JAXBElement<>(_SourceTypeSubtitle_QNAME, TextType.class, FeedType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "title", scope = FeedType.class)
    public JAXBElement<TextType> createFeedTypeTitle(TextType value) {
        return new JAXBElement<>(_SourceTypeTitle_QNAME, TextType.class, FeedType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateTimeType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DateTimeType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "updated", scope = FeedType.class)
    public JAXBElement<DateTimeType> createFeedTypeUpdated(DateTimeType value) {
        return new JAXBElement<>(_SourceTypeUpdated_QNAME, DateTimeType.class, FeedType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntryType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link EntryType }{@code >}
     */
    @XmlElementDecl(namespace = ATOMNAMESPACEURI, name = "entry", scope = FeedType.class)
    public JAXBElement<EntryType> createFeedTypeEntry(EntryType value) {
        return new JAXBElement<>(_Entry_QNAME, EntryType.class, FeedType.class, value);
    }

}
