//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.18 at 12:33:05 AM EDT 
//


package org.greenbuttonalliance.espi.resourceserver.web.model.usage;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ApnodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ApnodeType"&gt;
 *   &lt;restriction base="{http://naesb.org/espi}String8"&gt;
 *     &lt;enumeration value="AG"/&gt;
 *     &lt;enumeration value="CPZ"/&gt;
 *     &lt;enumeration value="DPZ"/&gt;
 *     &lt;enumeration value="LAP"/&gt;
 *     &lt;enumeration value="TH"/&gt;
 *     &lt;enumeration value="SYS"/&gt;
 *     &lt;enumeration value="CA"/&gt;
 *     &lt;enumeration value="DCA"/&gt;
 *     &lt;enumeration value="GA"/&gt;
 *     &lt;enumeration value="GH"/&gt;
 *     &lt;enumeration value="EHV"/&gt;
 *     &lt;enumeration value="ZN"/&gt;
 *     &lt;enumeration value="INT"/&gt;
 *     &lt;enumeration value="BUS"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ApnodeType")
@XmlEnum
public enum ApnodeType {


    /**
     * Aggregated Generation
     * 
     */
    AG,

    /**
     * Custom Price Zone
     * 
     */
    CPZ,

    /**
     * Default Price Zone
     * 
     */
    DPZ,

    /**
     * Load Aggregation Point
     * 
     */
    LAP,

    /**
     * Trading  Hub
     * 
     */
    TH,

    /**
     * System Zone
     * 
     */
    SYS,

    /**
     * Control Area
     * 
     */
    CA,

    /**
     * Designated Congestion Area
     * 
     */
    DCA,

    /**
     * generic aggregation
     * 
     */
    GA,

    /**
     * generic hub
     * 
     */
    GH,

    /**
     *  500 kV - Extra High Voltage aggregate price nodes
     * 
     */
    EHV,

    /**
     * Zone
     * 
     */
    ZN,

    /**
     * Interface
     * 
     */
    INT,

    /**
     * Bus
     * 
     */
    BUS;

    public String value() {
        return name();
    }

    public static ApnodeType fromValue(String v) {
        return valueOf(v);
    }

}
