//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.18 at 12:33:05 AM EDT 
//


package org.greenbuttonalliance.espi.resourceserver.web.model.usage;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnrollmentStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EnrollmentStatus"&gt;
 *   &lt;restriction base="{http://naesb.org/espi}String32"&gt;
 *     &lt;enumeration value="unenrolled"/&gt;
 *     &lt;enumeration value="enrolled"/&gt;
 *     &lt;enumeration value="enrolledPending"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "EnrollmentStatus")
@XmlEnum
public enum EnrollmentStatus {


    /**
     * Currently NOT enrolled in Tariff Rider
     * 
     */
    @XmlEnumValue("unenrolled")
    UNENROLLED("unenrolled"),

    /**
     * Currently enrolled in the Tariff Rider
     * 
     */
    @XmlEnumValue("enrolled")
    ENROLLED("enrolled"),

    /**
     * Currently pending enrollment in Tariff Rider
     * 
     */
    @XmlEnumValue("enrolledPending")
    ENROLLED_PENDING("enrolledPending");
    private final String value;

    EnrollmentStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EnrollmentStatus fromValue(String v) {
        for (EnrollmentStatus c: EnrollmentStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
