//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.18 at 12:33:05 AM EDT 
//


package org.greenbuttonalliance.espi.resourceserver.web.model.usage;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ParticipationCategoryMPM.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ParticipationCategoryMPM"&gt;
 *   &lt;restriction base="{http://naesb.org/espi}String4"&gt;
 *     &lt;enumeration value="Y"/&gt;
 *     &lt;enumeration value="N"/&gt;
 *     &lt;enumeration value="S"/&gt;
 *     &lt;enumeration value="L"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ParticipationCategoryMPM")
@XmlEnum
public enum ParticipationCategoryMPM {


    /**
     * Participates in both LMPM and SMPM
     * 
     */
    Y,

    /**
     * Not included in LMP price measures
     * 
     */
    N,

    /**
     * Participates in SMPM price measures
     * 
     */
    S,

    /**
     * Participates in LMPM price measures
     * 
     */
    L;

    public String value() {
        return name();
    }

    public static ParticipationCategoryMPM fromValue(String v) {
        return valueOf(v);
    }

}
