//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.18 at 12:33:05 AM EDT 
//


package org.greenbuttonalliance.espi.resourceserver.web.model.usage;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * [extension] List of programIDmappings
 * 
 * <p>Java class for ProgramIdMappings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProgramIdMappings"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://naesb.org/espi}IdentifiedObject"&gt;
 *       &lt;sequence maxOccurs="unbounded"&gt;
 *         &lt;element name="programIdMapping"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="tOUorCPPorConsumptionTier" type="{http://naesb.org/espi}tOUorCPPorConsumptionTier"/&gt;
 *                   &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *                   &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProgramIdMappings", propOrder = {
    "programIdMapping"
})
public class ProgramIdMappings
    extends IdentifiedObject
{

    @XmlElement(required = true)
    protected List<ProgramIdMappings.ProgramIdMapping> programIdMapping;

    /**
     * Gets the value of the programIdMapping property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the programIdMapping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProgramIdMapping().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProgramIdMappings.ProgramIdMapping }
     * 
     * 
     */
    public List<ProgramIdMappings.ProgramIdMapping> getProgramIdMapping() {
        if (programIdMapping == null) {
            programIdMapping = new ArrayList<ProgramIdMappings.ProgramIdMapping>();
        }
        return this.programIdMapping;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="tOUorCPPorConsumptionTier" type="{http://naesb.org/espi}tOUorCPPorConsumptionTier"/&gt;
     *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
     *         &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "toUorCPPorConsumptionTier",
        "code",
        "name",
        "note"
    })
    public static class ProgramIdMapping {

        @XmlElement(name = "tOUorCPPorConsumptionTier", required = true)
        @XmlSchemaType(name = "string")
        protected TOUorCPPorConsumptionTier toUorCPPorConsumptionTier;
        @XmlElement(required = true)
        protected java.lang.Object code;
        @XmlElement(required = true)
        protected java.lang.Object name;
        protected java.lang.Object note;

        /**
         * Gets the value of the toUorCPPorConsumptionTier property.
         * 
         * @return
         *     possible object is
         *     {@link TOUorCPPorConsumptionTier }
         *     
         */
        public TOUorCPPorConsumptionTier getTOUorCPPorConsumptionTier() {
            return toUorCPPorConsumptionTier;
        }

        /**
         * Sets the value of the toUorCPPorConsumptionTier property.
         * 
         * @param value
         *     allowed object is
         *     {@link TOUorCPPorConsumptionTier }
         *     
         */
        public void setTOUorCPPorConsumptionTier(TOUorCPPorConsumptionTier value) {
            this.toUorCPPorConsumptionTier = value;
        }

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.Object }
         *     
         */
        public java.lang.Object getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.Object }
         *     
         */
        public void setCode(java.lang.Object value) {
            this.code = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.Object }
         *     
         */
        public java.lang.Object getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.Object }
         *     
         */
        public void setName(java.lang.Object value) {
            this.name = value;
        }

        /**
         * Gets the value of the note property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.Object }
         *     
         */
        public java.lang.Object getNote() {
            return note;
        }

        /**
         * Sets the value of the note property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.Object }
         *     
         */
        public void setNote(java.lang.Object value) {
            this.note = value;
        }

    }

}
