//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.18 at 12:33:05 AM EDT 
//


package org.greenbuttonalliance.espi.resourceserver.web.model.usage;

import javax.xml.bind.annotation.*;


/**
 * [extension] Reference to a Tariff Rider.
 * 
 * <p>Java class for TariffRiderRef complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TariffRiderRef"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://naesb.org/espi}Object"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="riderType" type="{http://naesb.org/espi}String256"/&gt;
 *         &lt;element name="enrollmentStatus" type="{http://naesb.org/espi}EnrollmentStatus"/&gt;
 *         &lt;element name="effectiveDate" type="{http://naesb.org/espi}TimeType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TariffRiderRef", propOrder = {
    "riderType",
    "enrollmentStatus",
    "effectiveDate"
})
public class TariffRiderRef
    extends Object
{

    @XmlElement(required = true)
    protected String riderType;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected EnrollmentStatus enrollmentStatus;
    protected long effectiveDate;

    /**
     * Gets the value of the riderType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRiderType() {
        return riderType;
    }

    /**
     * Sets the value of the riderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRiderType(String value) {
        this.riderType = value;
    }

    /**
     * Gets the value of the enrollmentStatus property.
     * 
     * @return
     *     possible object is
     *     {@link EnrollmentStatus }
     *     
     */
    public EnrollmentStatus getEnrollmentStatus() {
        return enrollmentStatus;
    }

    /**
     * Sets the value of the enrollmentStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnrollmentStatus }
     *     
     */
    public void setEnrollmentStatus(EnrollmentStatus value) {
        this.enrollmentStatus = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     * 
     */
    public long getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     */
    public void setEffectiveDate(long value) {
        this.effectiveDate = value;
    }

}
